series: Basic OpenGL with GLFW
title: 3D Deferred Spot Lighting
author:
  name: David Erbelding
  email: daviderbelding@gmail.com
  github: https://github.com/Erbelding
description: Render deferred spot lights with a cone volume.
language: C++
tags:
  - Graphics
  - Optimization
extra_resources:
connections:
  - series: Basic OpenGL with GLFW
    title: 3D Deferred Point Lighting
  - series: Basic OpenGL with GLFW
    title: Spot Lighting
